[project]
name = "uea-ml-srcnn"
version = "0.1.0"
description = "SRCNN"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "kagglehub>=0.3.11",
    "keras>=3.9.2",
    "matplotlib>=3.10.1",
    "pillow>=11.2.1",
    "tensorflow>=2.19.0",
]
